data:
  train_path: "data/train.csv"
  test_path: "data/test.csv"
  target_column: "target"

preprocessing:
  handle_missing: true
  remove_outliers: true
  scale_features: true
  scaling_method: "standard"  # standard, minmax, robust

training:
  test_size: 0.2
  random_state: 42
  cv_folds: 3

models:
  random_forest:
    n_estimators: [100, 200]
    max_depth: [10, 20, null]
    min_samples_split: [2, 5]
  
  gradient_boosting:
    n_estimators: [100, 200]
    learning_rate: [0.01, 0.1]
    max_depth: [3, 5]
  
  svm:
    C: [0.1, 1, 10]
    kernel: ["rbf", "linear"]
  
  logistic_regression:
    C: [0.1, 1, 10]
    penalty: ["l1", "l2"]
    solver: ["liblinear"]

feature_engineering:
  create_interactions: true
  create_polynomials: false
  feature_selection: true
  max_features: 20

mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "ml_pipeline_experiment"

api:
  host: "0.0.0.0"
  port: 8000
  debug: false

